# DocOrchestrationScheduler Configuration Example
# Copy this file to schedules.yaml and customize for your needs

# Logging configuration
logging:
  level: INFO  # DEBUG, INFO, WARNING, ERROR
  directory: ./logs  # Directory for log files

# Notification settings
notifications:
  enabled: true  # Enable notifications
  type: "slack"  # Default notification type: "slack" or "desktop"

  # Slack configuration
  slack:
    webhook_url: "YOUR_SLACK_WEBHOOK_URL_HERE"

  # Desktop notification configuration (macOS only)
  desktop:
    sound: true  # Play sound with notification

# Scheduled jobs
jobs:
  # Gmail idea generation - Check for new emails daily at 3:00 AM
  - name: "Qwilo Ideas - Gmail Check"
    enabled: true
    pipeline_config: "qwilo_gmail_pipeline.yaml"  # Relative to DocOrchestrator directory
    command_args: "--generate-ideas"  # Only generate ideas, don't create documents
    timeout: 2100  # 35 minutes
    notify_on_success: true  # Send notification when ideas are generated
    notification_type: ""  # Empty = use global default (Slack)

    # Incremental processing - only process emails since last successful run
    incremental: true
    date_format: "%m%d%Y"  # Format: 01152025
    lookback_days: 0  # No overlap - start from day after last run

    schedule:
      type: daily
      time: "03:00"  # 3:00 AM Pacific
      timezone: America/Los_Angeles

  # Google Drive idea generation - Check for documents daily at 8:45 AM
  - name: "Qwilo Ideas - Google Drive Check"
    enabled: true
    pipeline_config: "qwilo_gdrive_pipeline.yaml"  # Relative to DocOrchestrator directory
    command_args: "--generate-ideas"  # Only generate ideas, don't create documents
    timeout: 2100  # 35 minutes
    notify_on_success: true  # Send notification when ideas are generated
    notification_type: ""  # Empty = use global default (Slack)

    # Note: Google Drive does not support incremental processing
    # The job will process all documents in the specified folder each time it runs

    schedule:
      type: daily
      time: "08:45"  # 8:45 AM Pacific
      timezone: America/Los_Angeles

  # Document generation - Process reviewed topics every 15 minutes
  - name: "Generate Documents - Every 15 Minutes"
    enabled: true
    pipeline_config: ""  # Not needed for --generate-all-pending
    command_args: "--generate-all-pending"  # Generate docs for all reviewed sessions
    timeout: 1800  # 30 minutes
    notify_on_success: false  # Notifications sent by orchestrator per document

    schedule:
      type: interval
      minutes: 15  # Run every 15 minutes
      timezone: America/Los_Angeles

  # ===== ADDITIONAL SCHEDULING EXAMPLES =====

  # Weekly Qwilo blog pipeline - Runs every Monday at 9 AM
  - name: "Weekly Qwilo Blog"
    enabled: false
    pipeline_config: "qwilo_pipeline.yaml"
    timeout: 1800
    incremental: true
    date_format: "%m%d%Y"
    lookback_days: 0
    schedule:
      type: cron
      day_of_week: mon
      hour: 9
      minute: 0
      timezone: America/Los_Angeles

  # Daily morning pipeline - Runs every weekday at 8 AM
  - name: "Daily Morning Pipeline"
    enabled: false  # Disabled by default
    pipeline_config: "~/Development/Scripts/DocOrchestrator/my_pipeline.yaml"  # Absolute path
    timeout: 3600  # 1 hour
    schedule:
      type: daily
      time: "08:00"  # HH:MM format
      timezone: America/Los_Angeles

  # Weekend pipeline - Runs Saturday and Sunday at 10 AM
  - name: "Weekend Pipeline"
    enabled: false
    pipeline_config: "weekend_pipeline.yaml"
    timeout: 3600
    schedule:
      type: cron
      day_of_week: sat,sun
      hour: 10
      minute: 0
      timezone: America/Los_Angeles

  # Every 6 hours pipeline
  - name: "Frequent Updates"
    enabled: false
    pipeline_config: "frequent_pipeline.yaml"
    timeout: 1800
    schedule:
      type: interval
      hours: 6
      minutes: 0
      timezone: America/Los_Angeles

  # Complex cron schedule - Every weekday at 2 PM and 6 PM
  - name: "Twice Daily Weekdays"
    enabled: false
    pipeline_config: "twice_daily_pipeline.yaml"
    timeout: 3600
    schedule:
      type: cron
      day_of_week: mon-fri  # Monday through Friday
      hour: 14,18  # 2 PM and 6 PM
      minute: 0
      timezone: America/Los_Angeles

  # ===== STAGED EXECUTION EXAMPLES =====

  # Stage 1: Generate ideas only (runs weekly, stacks up for later review)
  - name: "Generate Blog Ideas"
    enabled: false
    pipeline_config: "qwilo_pipeline.yaml"
    command_args: "--generate-ideas"  # Only generate ideas, don't generate docs
    timeout: 1800
    schedule:
      type: cron
      day_of_week: mon
      hour: 9
      minute: 0
      timezone: America/Los_Angeles

  # Stage 2: Process all pending reviews and generate documents (runs every 15 minutes)
  - name: "Generate Documents - Every 15 Minutes"
    enabled: false
    pipeline_config: ""  # Not needed for --generate-all-pending
    command_args: "--generate-all-pending"  # Generate docs for all reviewed sessions
    timeout: 1800  # 30 minutes
    schedule:
      type: interval
      minutes: 15
      timezone: America/Los_Angeles

  # Google Drive source example - Process documents from Google Drive folder
  - name: "Qwilo Ideas - Google Drive"
    enabled: false
    pipeline_config: "qwilo_gdrive_pipeline.yaml"  # Uses Google Drive as source
    command_args: "--generate-ideas"
    timeout: 2100  # 35 minutes
    schedule:
      type: daily
      time: "16:00"  # 4:00 PM Pacific
      timezone: America/Los_Angeles

  # Note: For manual review workflow, you would manually run:
  #   python orchestrator.py --list-pending
  #   python orchestrator.py --review --session SESSION_ID
  #   python orchestrator.py --generate-docs --session SESSION_ID

# Schedule Type Options:
#
# 1. cron - Cron-style scheduling
#    day_of_week: mon, tue, wed, thu, fri, sat, sun, or combinations (mon-fri, sat,sun)
#    hour: 0-23 or comma-separated list (9, 14,18)
#    minute: 0-59
#    timezone: Any pytz timezone (America/Los_Angeles, America/New_York, UTC, etc.)
#
# 2. daily - Run once per day at specific time
#    time: "HH:MM" format (e.g., "09:00", "14:30")
#    timezone: Any pytz timezone
#
# 3. interval - Run repeatedly at fixed intervals
#    hours: Number of hours between runs
#    minutes: Number of minutes between runs
#    timezone: Any pytz timezone
#
# Incremental Processing Options:
#   incremental: true/false - Enable state tracking to avoid re-processing same data
#   date_format: Format string for start_date parameter (e.g., "%m%d%Y" = "01152025")
#   lookback_days: Number of days to overlap with previous run (0 = no overlap)
#
#   How it works:
#   - First run: No start_date injected, processes all data
#   - Subsequent runs: Calculates start_date as (last_run + 1 day - lookback_days)
#   - State persisted in scheduler_state.json
#   - Failed jobs don't update last_run, so next attempt uses same start_date
#
# Staged Execution (New Feature):
#   command_args: Optional command-line arguments for staged execution modes
#
#   Examples:
#   - "--generate-ideas" - Only generate ideas, don't create documents
#   - "--review --session SESSION_ID" - Review a specific session (advanced)
#   - "--generate-docs --session SESSION_ID" - Generate docs for reviewed session (advanced)
#
#   Staged workflow benefits:
#   - Separate idea generation from document creation
#   - Stack up multiple idea sessions for batch review
#   - Manual quality control before committing to document generation
#
#   Typical staged workflow:
#   1. Schedule automated idea generation (weekly/daily)
#   2. Manually review pending sessions when convenient
#   3. Manually trigger document generation for approved topics
#
# Notes:
#   - Set enabled: false to disable a job without removing it
#   - Pipeline configs can be relative (to DocOrchestrator dir) or absolute paths
#   - Timeout is in seconds (1800 = 30 min, 3600 = 1 hour)
#   - Jobs run with --yes flag (auto-confirm all prompts)
#   - command_args is optional; without it, jobs run in full sequential mode (default)
